# Generated by Django 3.0.3 on 2020-03-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='twitteruser',
            new_name='follow_target',
        ),
        migrations.AlterField(
            model_name='notification',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
