# Generated by Django 3.0.4 on 2020-03-31 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20200303_0242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='follow_target',
            new_name='recipient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='viewed',
        ),
    ]
