# Generated by Django 3.0.4 on 2020-03-31 19:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0002_remove_twitteruser_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteruser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='twitteruser',
            name='display_name',
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='followers',
            field=models.ManyToManyField(related_name='twitter_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='following',
            field=models.ManyToManyField(related_name='twitter_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
